apiVersion: v1
kind: Service
metadata:
  name: ai-story-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: ai-story
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}